version: '2'
services:
  calltenderscraping-app:
    image: calltenderscraping
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://calltenderscraping-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=CallTenderScraping
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  calltenderscraping-mongodb:
    extends:
      file: mongodb.yml
      service: calltenderscraping-mongodb
